version: '3'
services:
  isaiah:
    image: mosswill/isaiah:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - my_docker_hosts:/docker_hosts
    environment:
      AUTHENTICATION_SECRET: "your-very-long-and-mysterious-secret"
      MULTI_HOST_ENABLED: "TRUE"
