version: '3'
services:
  isaiah:
    image: mosswill/isaiah:latest
    restart: unless-stopped
    networks:
      - global
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AUTHENTICATION_SECRET: "your-very-long-and-mysterious-secret"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.isaiah.rule=Host(`your-server.tld`)"
      - "traefik.http.routers.isaiah.service=isaiah-server"
      - "traefik.http.services.isaiah-server.loadbalancer.server.port=80"
      - "traefik.http.services.isaiah-server.loadbalancer.server.scheme=http"

      # Depending on your setup, you may also need
      # - "traefik.http.routers.isaiah.entrypoints=websecure"
      # - "traefik.http.routers.isaiah.tls=true"
      # - "traefik.http.routers.isaiah.tls.certresolver=tlschallenge"


  # Assumption made : another container running Traefik 
  #                   was configured and started beforehand
  #                   and attached to the network "global"

networks:
  # Assumption made : network "global" was created beforehand
  # with            : docker network create global
  global:
    external: true
